# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"explore_df": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://ryanfras.github.io/lazy/"

git_url = "https://github.com/ryanfras/lazy/tree/master/"

def custom_doc_links(name): return None
